# Generated by Django 3.2.17 on 2023-10-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
    ]
