# Generated by Django 4.2 on 2023-06-30 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='現場')),
                ('memo', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='メモ')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='データ更新日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '現場',
                'verbose_name_plural': '現場一覧',
                'db_table': 'location',
            },
        ),
    ]
