# Generated by Django 3.2.17 on 2023-10-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_sensors_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.location', verbose_name='現場'),
        ),
    ]
