# Generated by Django 3.2.17 on 2023-10-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_sensors_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensors',
            name='local',
        ),
    ]
