# Generated by Django 3.2.17 on 2023-10-25 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0025_sensors_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='測定点'),
        ),
    ]
