# Generated by Django 3.2.17 on 2023-02-17 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='現場')),
                ('memo', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='メモ')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '現場',
                'verbose_name_plural': '現場一覧',
                'db_table': 'location',
            },
        ),
    ]
