# Generated by Django 3.2.17 on 2023-02-22 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_location_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='データ更新日'),
        ),
    ]
