# Generated by Django 3.2.17 on 2023-02-22 06:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_location_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(blank=True, default='', max_length=127, null=True, verbose_name='センサー')),
                ('note', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='補足')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.location', verbose_name='現場')),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
    ]
