# Generated by Django 3.2.17 on 2023-02-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sensors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensors',
            options={'verbose_name': 'センサー', 'verbose_name_plural': 'センサー一覧'},
        ),
    ]
