# Generated by Django 3.2.17 on 2023-03-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_result_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='place',
            new_name='site',
        ),
        migrations.AlterUniqueTogether(
            name='sensors',
            unique_together={('site', 'device')},
        ),
    ]
